
add_newline = false

[line_break]
disabled = true

[aws]
style = ""
symbol = "â˜ "

[azure]
symbol = "â˜ "
style = " "

[battery]
full_symbol = "âŠ™ "
charging_symbol = "âŠ• "
discharging_symbol = "âŠ– "

[[battery.display]]
threshold = 10
style = ""

[buf]
symbol = "buf "
style = ""

[c]
style = ""

[character]
success_symbol = "âœ "
error_symbol = "âœ— "

[cmake]
style = ""

[cobol]
style = ""

[cmd_duration]
style = ""

[conda]
style = ""
symbol = "ğ•”"

[container]
style = ""

[crystal]
style = ""
symbol = "âŒ¬ "

[daml]
style = ""

[dart]
style = ""
symbol = "ğ•• "

[deno]
style = ""
symbol = "deno "


[directory]
style = ""
read_only = "ğŸ”’"
read_only_style = ""
home_symbol = "~"
truncation_length = 3

[docker_context]
style = ""
symbol = "âƒ "

[dotnet]
symbol = "ğŸ¥… "
style = ""

[elixir]
symbol = "ğŸ”® "
style = ""

[elm]
symbol = "ğŸŒ³ "
style = ""

[env_var]
style = ""

[erlang]
symbol = "î± "
style = ""

[fill]
symbol = "-"
style = ""

[gcloud]
symbol = "â˜ "
style = ""

[git_branch]
style = ""
symbol = "âŒ¥ "

[git_commit]
style = ""
commit_hash_length = 4
tag_symbol = "âŒ‚ "

[git_state]
style = ""
cherry_pick = "[â‡ PICKING]"

[git_metrics]
added_style = ""
deleted_style = ""

[git_status]
style = ""
conflicted = "ğŸ³"
ahead = "ğŸğŸ’¨"
behind = "ğŸ˜°"
diverged = "ğŸ˜µ"
up_to_date = "âœ“"
untracked = "ğŸ¤·"
stashed = "ğŸ“¦"
modified = "ğŸ“"
staged = '++\($count\)'
renamed = "ğŸ‘…"
deleted = "ğŸ—‘"

[golang]
style = ""
format = "via Go $version "

[haskell]
symbol = "Î» "
style = ""

[helm]
symbol = "âˆ "
style = ""

[hostname]
ssh_symbol = "â˜ "
style = ""

[java]
style = ""
symbol = "â˜† "

[jobs]
style = ""
symbol = "+ "
number_threshold = 4
symbol_threshold = 0

[julia]
style = ""
symbol = "à®ƒ "

[kotlin]
style = ""
symbol = "ğŸ…º "

[kubernetes]
style = ""
symbol = "â˜¸ "

[localip]
ssh_only = false
style = ""
disabled = true

[lua]
symbol = "â˜¾ "
style = ""

[memory_usage]
symbol = "âˆƒ"
style = ""

[hg_branch]
symbol = "âŒ¥ "
style = ""

[nim]
symbol = "â™› "
style = ""

[nix_shell]
symbol = "â„ "
style = ""

[nodejs]
symbol = "â™» "
style = ""

[ocaml]
symbol = "â‹Œ "
style = ""

[openstack]
style = ""
symbol = "â˜ "

[package]
style = ""
symbol = "â "

[perl]
style = ""
symbol = "perl "

[php]
style = ""
symbol = "php "

[pulumi]
style = ""
symbol = "pulumi "

[purescript]
style = ""
symbol = "<=> "

[python]
style = ""
symbol = "python "

[rlang]
style = ""
symbol = "R "

[red]
style = ""
symbol = "red "

[ruby]
style = ""
symbol = "â™¢ "

[rust]
style = ""
symbol = "rust "

[scala]
style = ""
symbol = "scala "

[shell]
style = "shell "

[shlvl]
style = ""
symbol = "shlvl "

[singularity]
style = ""

[spack]
style = ""
symbol = "spack "

[status]
style = ""
symbol = "âœ– "
success_symbol = "âœ” "
format = '[\[$symbol$common_meaning$signal_name$maybe_int\]]($style) '
map_symbol = true
disabled = false

[sudo]
style = ""
symbol = "âœš "
disabled = false

[swift]
style = ""
symbol = "swift "

[terraform]
style = ""
symbol = "ğŸŒ‘ "

[time]
style = ""
disabled = true
format = '[\[ $time \]]($style) '
time_format = "%T"

[username]
style_user = ""
style_root = ""
format = "$user "
disabled = true
show_always = true

[vagrant]
style = ""
symbol = "â± "

[vlang]
style = ""
symbol = "V "

[vcsh]
style = ""
symbol = ""

[zig]
style = ""
symbol = "âš¡ "

